SUMMARY = "epp-v2 image for the FRDM-IMX95 (LPDDR4x)"
LICENSE = "MIT"

require recipes-core/images/core-image-minimal.bb

IMAGE_FEATURES += "ssh-server-openssh package-management"

IMAGE_INSTALL:append = " \
    kernel-modules \
    ${@bb.utils.contains('DISTRO_FEATURES', 'xen', 'xen-tools', '', d)} \
    ${EPP_EXTRA_PACKAGES} \
"

# Root password from board.conf (EPP_ROOT_PASSWORD_HASH is generated by
# scripts/yocto-build.sh)
inherit extrausers

python () {
    pw_hash = d.getVar('EPP_ROOT_PASSWORD_HASH')
    if pw_hash:
        d.setVar('EXTRA_USERS_PARAMS', "usermod -p '%s' root;" % pw_hash)
    else:
        bb.warn("EPP_ROOT_PASSWORD_HASH is empty: root password not set by meta-epp-v2. "
                "Build through scripts/yocto-build.sh to apply board.conf.")
}

# Boot script, device tree overlays and the Xen hypervisor on the FAT boot
# partition (mounted at /boot on the target)
IMAGE_BOOT_FILES:append = " \
    boot.scr \
    devicetree/*.dtbo;overlays/ \
    ${@bb.utils.contains('DISTRO_FEATURES', 'xen', 'xen', '', d)} \
"
do_image_wic[depends] += " \
    epp-v2-bootscript:do_deploy \
    epp-v2-overlays:do_deploy \
    ${@bb.utils.contains('DISTRO_FEATURES', 'xen', 'xen:do_deploy', '', d)} \
"
IMAGE_ROOTFS_EXTRA_SPACE = "4194304"