#!/bin/bash
# Runs INSIDE the build container (started by docker-run.sh).
# Syncs the i.MX BSP, sets up the build dir, adds meta-epp-v2, writes
# conf/auto.conf from board.conf and builds the image.
#
# Set SKIP_SYNC=1 to skip "repo sync" on rebuilds.
set -e

for var in EPP_DIR VERSION BRANCH MANIFEST REMOTE MACHINE DISTRO IMAGES DOCKER_WORKDIR DL_DIR SSTATE_DIR; do
    if [ -z "${!var}" ]; then
        echo "Error: ${var} is not set (run this script through docker-run.sh)" >&2
        exit 1
    fi
done

BUILD_DIR_NAME="build_${MACHINE}"

echo "========================================="
echo "Building epp-v2 i.MX Yocto BSP"
echo "========================================="
echo "Version:  ${VERSION} (${BRANCH})"
echo "Machine:  ${MACHINE}"
echo "Distro:   ${DISTRO}"
echo "Images:   ${IMAGES}"
echo "Build:    ${DOCKER_WORKDIR}/${BUILD_DIR_NAME}"
echo "========================================="

cd "${DOCKER_WORKDIR}"

if [ "${SKIP_SYNC}" = "1" ] && [ -d .repo ]; then
    echo "Skipping repo sync (SKIP_SYNC=1)"
else
    repo init -u "${REMOTE}" -b "${BRANCH}" -m "${MANIFEST}"
    repo sync -j"$(nproc)"
fi

# Set up (or re-enter) the build directory; both scripts cd into it.
# setup-environment unsets MACHINE and DISTRO, so keep a copy.
EPP_MACHINE="${MACHINE}"
EPP_DISTRO="${DISTRO}"
if [ -f "${BUILD_DIR_NAME}/conf/local.conf" ]; then
    source setup-environment "${BUILD_DIR_NAME}"
else
    EULA=1 MACHINE="${MACHINE}" DISTRO="${DISTRO}" source imx-setup-release.sh -b "${BUILD_DIR_NAME}"
fi
export MACHINE="${EPP_MACHINE}" DISTRO="${EPP_DISTRO}"

# Add meta-epp-v2 (idempotent)
LAYER_PATH="${EPP_DIR}/meta-epp-v2"
if ! grep -q "${LAYER_PATH}" conf/bblayers.conf; then
    echo "BBLAYERS += \"${LAYER_PATH}\"" >> conf/bblayers.conf
    echo "Added ${LAYER_PATH} to bblayers.conf"
fi

# Generate conf/auto.conf from board.conf (regenerated on every build, so
# edit board.conf / config.sh rather than auto.conf).
source "${EPP_DIR}/board.conf"

# Deterministic salt so the hash (and therefore the rootfs signature) only
# changes when the password or hostname changes.
SALT="$(printf '%s' "${EPP_HOSTNAME}${EPP_ROOT_PASSWORD}" | sha256sum | cut -c1-16)"
ROOT_HASH="$(openssl passwd -6 -salt "${SALT}" "${EPP_ROOT_PASSWORD}")"
# extrausers evaluates the parameters in a shell, so escape '$'
ROOT_HASH_ESCAPED="${ROOT_HASH//\$/\\\$}"

cat > conf/auto.conf <<EOF
# GENERATED by meta-epp-v2 scripts/yocto-build.sh from board.conf and config.sh.
# Do not edit, changes are overwritten on the next build.

MACHINE = "${MACHINE}"
DISTRO = "${DISTRO}"

DL_DIR = "${DL_DIR}"
SSTATE_DIR = "${SSTATE_DIR}"
# Keep the hash equivalence database next to the sstate cache, so the cache
# stays reusable when the build directory is deleted
BB_HASHSERVE_DB_DIR = "${SSTATE_DIR}"

BB_NUMBER_THREADS = "${BB_NUMBER_THREADS}"
PARALLEL_MAKE = "-j ${PARALLEL_MAKE_JOBS}"
BB_PRESSURE_MAX_MEMORY = "10000"
GNU_MIRROR = "https://ftp.gnu.org/gnu"

PACKAGE_CLASSES = "package_deb"

# epp-v2 distro policy (meta-epp-v2/conf/epp-v2.conf)
require conf/epp-v2.conf

# Board settings
EPP_HOSTNAME = "${EPP_HOSTNAME}"
EPP_ROOT_PASSWORD_HASH = "${ROOT_HASH_ESCAPED}"
EPP_SSH_ROOT_LOGIN = "${EPP_SSH_ROOT_LOGIN}"
EPP_OVERLAYS = "${EPP_OVERLAYS}"
EPP_FDTFILE = "${EPP_FDTFILE}"
EPP_EXTRA_PACKAGES = "${EPP_EXTRA_PACKAGES}"
EOF

echo "Starting build..."
bitbake ${IMAGES}

# Shortcut to the output images: <repo>/images
DEPLOY_DIR="${DOCKER_WORKDIR}/${BUILD_DIR_NAME}/tmp/deploy/images/${MACHINE}"
ln -sfn "$(realpath --relative-to="${EPP_DIR}" "${DEPLOY_DIR}")" "${EPP_DIR}/images"

echo ""
echo "========================================="
echo "✅ Build completed successfully!"
echo "Images: ${EPP_DIR}/images -> ${DEPLOY_DIR}"
echo "========================================="
