SUMMARY = "epp-v2 device tree overlays for external modules"
DESCRIPTION = "Builds every *.dtso in files/ against the kernel headers and \
deploys the .dtbo files. epp-v2-image puts them on the boot partition under \
overlays/, and the U-Boot boot script applies the ones listed in EPP_OVERLAYS. \
For EPP_XEN_ZEPHYR_PASSTHROUGH it also generates the Xen partial device tree \
epp-zephyr-pt.dtb and the pin mux overlay epp-zephyr-pt-pins.dtbo."

inherit devicetree

COMPATIBLE_MACHINE = "imx95-15x15-lpddr4x-frdm"

# Hardware passed through to the Zephyr DomU: one fragment pair per device,
# epp-zephyr-<name>-pt.dtsi (node for the partial device tree) and
# epp-zephyr-<name>-pins.dtsi (pin group for the pinctrl hog)
EPP_XEN_ZEPHYR_PT_DEVICES = "gpio2 lpi2c4"

SRC_URI = " \
    file://epp-example.dtso \
    ${@' '.join('file://epp-zephyr-%s-pt.dtsi file://epp-zephyr-%s-pins.dtsi' % (n, n) for n in d.getVar('EPP_XEN_ZEPHYR_PT_DEVICES').split())} \
"

# Sources to compile: the overlays from files/ plus the generated files
DT_FILES_PATH = "${WORKDIR}/epp-dts"

do_configure[cleandirs] += "${DT_FILES_PATH}"
do_configure[vardeps] += "EPP_XEN_ZEPHYR_PASSTHROUGH"
do_configure() {
    cp ${S}/*.dtso ${DT_FILES_PATH}/

    pt="${EPP_XEN_ZEPHYR_PASSTHROUGH}"
    [ -n "$pt" ] || return 0

    # Partial device tree for the Zephyr DomU (/chosen/domU2 module
    # multiboot,device-tree): the /gic placeholder Xen expects, and the
    # devices under /passthrough
    out=${DT_FILES_PATH}/epp-zephyr-pt.dts
    cat > $out <<HDR
// Generated by epp-v2-overlays for EPP_XEN_ZEPHYR_PASSTHROUGH="$pt"
/dts-v1/;

/ {
	#address-cells = <2>;
	#size-cells = <2>;

	gic: gic {
		#interrupt-cells = <3>;
		interrupt-controller;
	};

	passthrough {
		compatible = "simple-bus";
		ranges;
		#address-cells = <2>;
		#size-cells = <2>;

HDR
    for n in $pt; do cat ${S}/epp-zephyr-$n-pt.dtsi >> $out; done
    printf '\t};\n};\n' >> $out

    # Pin mux overlay: Xen disables the devices for Dom0, so Linux no longer
    # sets their pins. Set them once with the SCMI pinctrl hog instead.
    # pinctrl-0 is one property, hence one overlay for all devices.
    out=${DT_FILES_PATH}/epp-zephyr-pt-pins.dtso
    groups=""
    for n in $pt; do groups="$groups &pinctrl_epp_$n"; done
    cat > $out <<HDR
// Generated by epp-v2-overlays for EPP_XEN_ZEPHYR_PASSTHROUGH="$pt"
#include "imx95-pinfunc.h"

/dts-v1/;
/plugin/;

&scmi_iomuxc {
	pinctrl-0 = <&pinctrl_hog$groups>;

HDR
    for n in $pt; do cat ${S}/epp-zephyr-$n-pins.dtsi >> $out; done
    printf '};\n' >> $out
}

# Start from an empty build directory, so overlays removed from SRC_URI are
# not deployed (and put on the boot partition) from an older build
do_compile[cleandirs] += "${B}"
